services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn --host 0.0.0.0 app.main:app --reload
      "

  db:
    image: mysql:9.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - "db_data:/var/lib/mysql"

  adminer:
    depends_on:
      db:
        condition: service_healthy
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: