"""New Migration

Revision ID: 763b9ecb23bc
Revises: 
Create Date: 2025-05-22 08:24:41.024243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763b9ecb23bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('FINISHED', 'SEMI_FINISHED', 'RAW', name='productcategory'), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('product_image', sa.String(length=65535), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.Enum('MTR', 'MM', 'LTR', 'ML', 'CM', 'MG', 'GM', 'UNIT', 'PACK', name='unitofmeasure'), nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
